[project]
name = "toolsandogh"
dynamic = ["version"]
description = "A collection of Python scripts for iSCAT microscopy data analysis"
authors = [{ name = "Marco Heisig", email = "marco.heisig@mpl.mpg.de" }]
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
dependencies = [
    "bioio>=3.4",
    "bioio-dv>=1.2",
    "bioio-imageio>=1.3",
    "bioio-lif>=1.3",
    "bioio-nd2>=2.0",
    "bioio-ome-tiff>=1.4",
    "bioio-ome-zarr>=3.5",
    "bioio-tifffile>=1.3",
    "bioio-tiff-glob>=1.2",
    "dask>=2025.1",
    "fsspec>=2025.1",
    "imageio[ffmpeg]>=2.37",
    "imgrvt>=1.0",
    "jax>=0.5.0",
    "jaxtyping>=0.3",
    "numpy>=2.0",
    "ome-types>=0.6",
    "polars>=1.0",
    "pyarrow>=16.0",
    "scikit-image>=0.23",
    "scipy>=1.13",
    "tifffile>=2026.5",
    "tqdm>=4.66",
    "xarray>=2025.1",
]
keywords = ["tools", "utilities", "python", "microscopy"]

[project.urls]
Repository = "https://github.com/SandoghdarLab/toolsandogh"
Issues = "https://github.com/SandoghdarLab/toolsandogh/issues"

[dependency-groups]
dev = [
    "build>=1.2",
    "ruff>=0.15",
    "pre-commit>=3.7",
    "pyright[nodejs]>=1.1.400",
    "ty>=0.0.50",
    "pytest>=8.0",
    "python-lsp-server>=1.10",
    "numpydoc>=1.7",
    "setuptools>=80",
    "setuptools-scm>=8",
    "coverage>=5.0",
    "rendercanvas>=2.2",
    "twine>=5.0",
    "bokeh>=3.4",
]

[build-system]
requires = ["setuptools>80", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]

[tool.ruff]
line-length = 100
fix = true
exclude = ["notebooks"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes errors
    "I",   # isort
    "C",   # complexity
    "RET", # flake8-return
    "YTT", # Truthiness
    "TRY", # Try block errors
    "NPY201" # Use Numpy 2.0
]
ignore = [
    "C901",   # Function too complex
    "E501",   # Line too long (handled by line-length)
    "E402",   # Module level import not at top of file (isort handles this)
    "F722",   # Jaxtyping errors
    "RET504", # Unnecessary assignment before return
    "TRY003", # Long message outside exception class
]
unfixable = ["F821"] # Don't try to fix name definition

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",  # examples
    "SA01",  # see also section
    "ES01",  # extended summary
    "GL08",  # module/class docstrings
]

[tool.pyright]
pythonVersion = "3.11"
include = ["src"]
exclude = [".venv"]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/toolsandogh/tests"]

[tool.coverage.paths]
source = ["src"]
